### ISSUE TITLE
custom distro example

### ISSUE THREAD

**Issue by jicowan** [chef-partners/knife-vcair#18]
If you can't access the Internet to bootstrap the Chef client onto your server, you can use the custom distro file I posted at https://gist.github.com/jicowan/e19fcbea08a9c6e2b1b6 instead.  This will pull the Chef client [for CentOS] from a web server within your vCloud Air vDC.

**Comment by cheeseplus** [comment]
Closing this out as it isn't an issue as such but I've added the link to the Notes section of the README.md in bac8ce562c92a88d9933c2a845b84d084da24bf3

:+1:
