### ISSUE TITLE
Seems to require Chefdk 0.2.1 or ealier... 

### ISSUE THREAD

**Issue by fr0gger03** [chef-partners/knife-vcair#20]
Just downloaded Chefdk 0.2.2, and received the attached error, indicating a 
![screen shot 2014-10-02 at 11 06 43 am](https://cloud.githubusercontent.com/assets/5892826/4492980/cb5deff8-4a45-11e4-84b0-6f73ea1f775d.png)

**Comment by cheeseplus** [comment]
Moved the dep on Chef to be a development dep as per other knife-* plugins https://github.com/chef-partners/knife-vcair/pull/25

**Comment by cheeseplus** [comment]
Fixed! ce8e713b61119415a43e79e458d380b1954bc93b
