### ISSUE TITLE
knife vcair server list error

### ISSUE THREAD

**Issue by Angelicvorian** [chef-partners/knife-vcair#21]
Running knife vcair server list with the follow options set in knife, and getting the below error:
Knife.rb
  require 'Excon'
  knife[:vcair_api_host] = 'lab.myco.com'
  knife[:vcair_username] = 'me'
  knife[:vcair_password] = 'myself'
  knife[:vcair_org] = 'productdevelopment'
  knife[:vcair_vdc] = 'my-vdc'
  Excon.defaults[:ssl_verify_peer] = false

When trying to run the above command i am seeing the following error:

DEBUG: vcair_api_version
DEBUG: vcair_show_progress
DEBUG: Using fog version: 1.24.0
c:/Ruby193/lib/ruby/gems/1.9.1/gems/knife-vcair-0.6.0/lib/chef/knife/vcair_helpe
rs.rb:24:in `vdc': undefined method `vdcs' for nil:NilClass (NoMethodError)
        from c:/Ruby193/lib/ruby/gems/1.9.1/gems/knife-vcair-0.6.0/lib/chef/knif
e/vcair_vm_list.rb:35:in `query_resource'
        from c:/Ruby193/lib/ruby/gems/1.9.1/gems/knife-cloud-1.0.1/lib/chef/knif
e/cloud/list_resource_command.rb:35:in `execute_command'
        from c:/Ruby193/lib/ruby/gems/1.9.1/gems/knife-cloud-1.0.1/lib/chef/knif
e/cloud/command.rb:51:in `run'
        from c:/Ruby193/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/ch
ef/knife.rb:493:in `run_with_pretty_exceptions'
        from c:/Ruby193/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/ch
ef/knife.rb:174:in `run'
        from c:/Ruby193/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/ch
ef/application/knife.rb:139:in `run'
        from c:/Ruby193/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/bin/kn
ife:25:in `<top (required)>'
        from c:/Ruby193/bin/knife:23:in `load'
        from c:/Ruby193/bin/knife:23:in `<main>'

Any ideas?

Thanks
Chris

**Comment by cheeseplus** [comment]
This is almost definitely an issue with the config value knife[:vcair_vdc]

https://github.com/chef-partners/knife-vcair/blob/master/lib/chef/knife/vcair_helpers.rb#L22-L28

**Comment by cheeseplus** [comment]
I realize that wasn't the most complete comment but after some testing it seems that setting `knife[:vcair_vdc]` only works if it matches `knife[:vcair_org]`. This was against vCloud Air - p3v11-vcd.vchs.vmware.com.

@Angelicvorian were you doing this against vCloud Air or was this an internal vCloud Director?

**Comment by Angelicvorian** [comment]
@cheeseplus Looks like it's vCloud Director. I have another test environment in a VMWare hosted system so I'll try that as well and see how i get on.
Thanks for the help!

**Comment by cheeseplus** [comment]
Going to close this as we aren't explicitly supporting vCloud Director (at this time*) with the plugin as the vCloud Air API is diverging from vCD but we may be revisiting this in the future with a separate plugin.
