### ISSUE TITLE
Support for internal vCloud Director

### ISSUE THREAD

**Issue by cstewart87** [chef-partners/knife-vcair#22]
Does this plugin support an internal implementation of vCloud Director?  If so, is there support for creating vApps?

**Comment by cheeseplus** [comment]
@cstewart87 the API is vCloud Director underneath but currently we are mapping vApps directly to VMs. So it's something that the API supports but we don't have any support for at the moment.

**Comment by cheeseplus** [comment]
Going to close this as we aren't explicitly supporting vCloud Director (at this time*) with the plugin as the vCloud Air API is diverging from vCD but we may be revisiting this in the future with a separate plugin.

(same as https://github.com/chef-partners/knife-vcair/issues/21)
