### ISSUE TITLE
Knife vcair Plugin Install

### ISSUE THREAD

**Issue by pknath19** [chef-partners/knife-vcair#24]
The error I am getting now is on Windows 7 with 0.4.0.  When I look at the GEM folder for Knife-vcair 0.6.0 the directory has only the licence and help file. Nothing else.  I assume this is due to the version of CHEFDK I am using.   

PS C:\code\knife-vcair-master> gem build knife-vcair.gemspec
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
WARNING:  licenses is empty, but is recommended.  Use a license abbreviation from:
http://opensource.org/licenses/alphabetical
WARNING:  description and summary are identical
WARNING:  open-ended dependency on fog (>= 1.23) is not recommended
  if fog is semantically versioned, use:
    add_runtime_dependency 'fog', '~> 1.23'
WARNING:  pessimistic dependency on knife-cloud (~> 1.0.0) may be overly strict
  if knife-cloud is semantically versioned, use:
    add_runtime_dependency 'knife-cloud', '~> 1.0', '>= 1.0.0'
WARNING:  open-ended dependency on knife-windows (>= 0) is not recommended
  if knife-windows is semantically versioned, use:
    add_runtime_dependency 'knife-windows', '~> 0'
WARNING:  open-ended dependency on rake (>= 0, development) is not recommended
  if rake is semantically versioned, use:
    add_development_dependency 'rake', '~> 0'
WARNING:  open-ended dependency on activesupport (>= 0, development) is not recommended
  if activesupport is semantically versioned, use:
    add_development_dependency 'activesupport', '~> 0'
WARNING:  open-ended dependency on rspec-core (>= 0, development) is not recommended
  if rspec-core is semantically versioned, use:
    add_development_dependency 'rspec-core', '~> 0'
WARNING:  open-ended dependency on rspec-expectations (>= 0, development) is not recommended
  if rspec-expectations is semantically versioned, use:
    add_development_dependency 'rspec-expectations', '~> 0'
WARNING:  open-ended dependency on rspec-mocks (>= 0, development) is not recommended
  if rspec-mocks is semantically versioned, use:
    add_development_dependency 'rspec-mocks', '~> 0'
WARNING:  open-ended dependency on rspec_junit_formatter (>= 0, development) is not recommended
  if rspec_junit_formatter is semantically versioned, use:
    add_development_dependency 'rspec_junit_formatter', '~> 0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: knife-vcair
  Version: 0.6.0
  File: knife-vcair-0.6.0.gem
PS C:\code\knife-vcair-master>

**Comment by cheeseplus** [comment]
Those `fatal` notices at the top are relevant - without git installed the build doesn't work properly. That said I was able to build and install it under Windows it appears that I need to adjust alter the gemspec because of a dependency conflict created when used against Chef 12.

**Comment by pknath19** [comment]
I fixed my git issue.   The reason for this error is because the gemspec is pointing to chef-11.18.6-x86-mingw32 not Chef 12 Correct?

C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:2104:in `raise_if_con
flicts': Unable to activate chef-11.18.6-x86-mingw32, because mixlib-shellout-2.0.1-x86-mingw32 con
flicts with mixlib-shellout (~> 1.4), ohai-8.0.1 conflicts with ohai (~> 7.4), chef-zero-3.2.1 conf
licts with chef-zero (>= 2.2.1, ~> 2.2) (Gem::ConflictError)
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:1282:in
`activate'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:1316:in
`block in activate_dependencies'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:1302:in
`each'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:1302:in
`activate_dependencies'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:1284:in
`activate'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.0.0/rubygems.rb:198:in `rescue in try_
activate'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.0.0/rubygems.rb:195:in `try_activate'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.r
b:126:in `rescue in require'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.r
b:39:in `require'
        from C:/Users/nathp/.chefdk/gem/ruby/2.0.0/gems/knife-vcair-0.6.0/lib/chef/knife/vcair_help
ers.rb:6:in `<top (required)>'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:35:in `l
oad'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:35:in `b
lock in load_commands'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:35:in `e
ach'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:35:in `l
oad_commands'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/knife.rb:126:in `load_commands'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/knife.rb:146:in `list_commands'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:195:in `print_help_
and_exit'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:162:in `validate_an
d_parse_options'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:137:in `run'
        from C:/opscode/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
        from C:/opscode/chefdk/bin/knife:52:in `load'
        from C:/opscode/chefdk/bin/knife:52:in `<main>'
PS C:\Code\knife-vcair>


'

**Comment by cheeseplus** [comment]
Correct and this is what this https://github.com/chef-partners/knife-vcair/pull/25 will relax/fix

**Comment by cheeseplus** [comment]
Resolved in ce8e713b61119415a43e79e458d380b1954bc93b
