### ISSUE TITLE
Subscription or On-demand Service?

### ISSUE THREAD

**Issue by cstewart87** [chef-partners/knife-vcair#28]
Does this plugin support a subscription based or on demand service with vCloud Air?  I'm testing against an on-demand account and I'm having some issues.

**Comment by mattray** [comment]
@adamleff and I will take a look into the issue this week. AFAIK it hasn't been explicitly tested.

**Comment by adamleff** [comment]
It appears that Fog does support talking to vCloud Air OnDemand but needs a bit of coaxing.  Specifically, we need to override the API path when setting up the Fog instance as the API path is different between the subscription service and the OnDemand service.

I'm going to be doing some additional tests, and if I can confirm this hypothesis, I'll submit a PR to address this.  I'll update this issue once I know more.

**Comment by adamleff** [comment]
PR #30 opened to allow you to override the path which is required to use this knife plugin with vCloud Air OnDemand.  I have tested it against OnDemand and it works with this fix.  The PR also updates the README with details on what you need to set the path to.

As soon as this PR is reviewed and merged, I'll cut a release of the gem and close out this issue.  Thanks for the report.

**Comment by adamleff** [comment]
I have a 0.7.0 version of the gem ready, but I do not have the appropriate rights to push up the update to RubyGems.  As soon as I get that squared away, I'll release 0.7.0.  Thanks for your patience!

**Comment by adamleff** [comment]
0.7.0 has been released to rubygems. :smile: Thanks again for the report.
